description: |
  A live interactive family friendly digital theatre show based on the true story of Valentina Tereshkova: the first woman in history to go into outer space.
footer: |
  Valentina Star Dreamer has been made possible thanks to: <br>
  [Haste Theatre](https://hastetheatre.com), [Mouths of Lions](https://mouthsoflions.co.uk), [The Place Bedford](https://theplacebedford.org.uk), and Arts Council England.
